export const EDIT_FILMS_REQUEST = "EDIT_FILM_REQUEST";
export const EDIT_FILMS_SUCCESS = "EDIT_FILM_SUCCESS";
export const EDIT_FILMS_FAIL = "EDIT_FILM_FAIL";
export const EDIT_FILMS_CLEAR = "EDIT_FILM_CLEAR";