export const DELETE_FILMS_REQUEST = "DELETE_FILM_REQUEST";
export const DELETE_FILMS_SUCCESS = "DELETE_FILM_SUCCESS";
export const DELETE_FILMS_FAIL = "DELETE_FILM_FAIL";
export const CLEAR_DELETE_FILMS= "CLEAR_DELETE_FILMS";