export const PERSONAL_REQUEST = "PERSONAL_REQUEST";
export const PERSONAL_SUCCESS = "PERSONAL_SUCCESS";
export const PERSONAL_FAIL = "PERSONAL_FAIL";

export const PERSONAL_INFO = "PERSONAL_INFO";

//EDIT
export const EDIT_PERSONAL_REQUEST = "EDIT_PERSONAL_REQUEST";
export const EDIT_PERSONAL_SUCCESS = "EDIT_PERSONAL_SUCCESS";
export const EDIT_PERSONAL_FAIL = "EDIT_PERSONAL_FAIL";