export const MOVIE_THEATER_REQUEST = "MOVIE_THEATER_REQUEST";
export const MOVIE_THEATER_SUCCESS = "MOVIE_THEATER_SUCCESS";
export const MOVIE_THEATER_FAIL = "MOVIE_THEATER_FAIL";

export const MOVIE_THEATER_CLUSTER_REQUEST = "MOVIE_THEATER_CLUSTER_REQUEST";
export const MOVIE_THEATER_CLUSTER_SUCCESS = "MOVIE_THEATER_CLUSTER_SUCCESS";
export const MOVIE_THEATER_CLUSTER_FAIL = "MOVIE_THEATER_CLUSTER_FAIL";