export const BOOKING_TICKET_REQUEST = "BOOKING_TICKET_REQUEST";
export const BOOKING_TICKET_SUCCESS = "BOOKING_TICKET_SUCCESS";
export const BOOKING_TICKET_FAIL = "BOOKING_TICKET_FAIL";
export const BOOKING_SEAT = "BOOKING_SEAT";
export const CHOOSING_SEAT = "CHOOSING_SEAT";

export const BUY_TICKET_REQUEST = "BUY_TICKET_REQUEST";
export const BUY_TICKET_SUCCESS = "BUY_TICKET_SUCCESS";
export const BUY_TICKET_FAIL = "BUY_TICKET_FAIL";
export const CLEAR_DATA_TICKET = "CLEAR_DATA_TICKET";
export const REDIRECT_ANTD = "REDIRECT_ANTD";
export const CHANGE_TABPANE = "CHANGE_TABPANE";


export const HISTORY_TICKET_REQUEST = "HISTORY_TICKET_REQUEST";
export const HISTORY_TICKET_SUCCESS = "HISTORY_TICKET_SUCCESS";
export const HISTORY_TICKET_FAIL = "HISTORY_TICKET_FAIL";
