export const MANAGE_USER_REQUEST = "MANAGE_USER_REQUEST";
export const MANAGE_USER_SUCCESS = "MANAGE_USER_SUCCESS";
export const MANAGE_USER_FAIL = "MANAGE_USER_FAIL";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";


export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const SELECT_USER = "SELECT_USER";