export const ADD_NEW_FILMS_REQUEST = "ADD_NEW_FILM_REQUEST";
export const ADD_NEW_FILMS_SUCCESS = "ADD_NEW_FILM_SUCCESS";
export const ADD_NEW_FILMS_FAIL = "ADD_NEW_FILM_FAIL";
export const CLEAR_NEW_FILMS = "CLEAR_NEW_FILMS";